# Generated by Django 5.1.4 on 2025-01-11 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
        ('Catalog', '0002_alter_product_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('quoteId', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('document_date', models.DateField(null=True)),
                ('status', models.CharField(choices=[('Quote', 'Quote'), ('Ready For Review', 'Ready'), ('Work Order', 'Workorder'), ('Invoice', 'Invoice'), ('Canceled', 'Canceled'), ('Paid', 'Paid')], default='Quote', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.company')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price_per_item', models.DecimalField(decimal_places=2, max_digits=10)),
                ('list_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalog.product')),
                ('quoteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Order.quote')),
            ],
            options={
                'verbose_name_plural': 'Quote Items',
                'ordering': ['list_order'],
            },
        ),
    ]
