# Generated by Django 5.1.4 on 2025-01-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
